name: Publish NuGet Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'MyLibrary/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore MyLibrary/MyLibrary.csproj

      - name: Build project
        run: dotnet build MyLibrary/MyLibrary.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack MyLibrary/MyLibrary.csproj --configuration Release --no-build --output ./nupkgs

      - name: Push package to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GH_NUGET_TOKEN }} --skip-duplicate
