name: Publish NuGet Package

on:
  push:
    branches:
      - main
    paths:
      - '**.csproj'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Pack NuGet Package
        run: dotnet pack MyLibrary/MyLibrary.csproj --configuration Release

      - name: Publish to GitHub Packages
        run: dotnet nuget push MyLibrary/nupkg/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
